export const traits = [
  {
    type: 'select',
    name: 'draggable',
    label: 'Locked',
    options: [
      { label: 'Draggable', value: true },
      { label: 'Locked', value: false },
    ],
  },
  {
    type: 'ggb-id-disabled',
    label: 'Id',
  },
  {
    type: 'select',
    name: 'appName',
    changeProp: true,
    options: [
      { value: 'classic', name: 'Classic' },
      { value: 'graphing', name: 'Graphing' },
      { value: 'geometry', name: 'Geometry' },
      { value: '3d', name: '3D' },
      { value: 'suite', name: 'Suite' },
      { value: 'evaluator', name: 'Evaluator' },
      { value: 'scientific', name: 'Scientific' },
      { value: 'notes', name: ' Notes' },
    ],
  },
  {
    type: 'text',
    name: 'material_id',
    changeProp: true,
    label: 'Share Code',
    placeholder: 'code',
  },
  {
    type: 'number',
    name: 'width',
    changeProp: true,
    label: 'Width',
  },
  {
    type: 'number',
    name: 'height',
    changeProp: true,
    label: 'Height',
  },
  {
    type: 'checkbox',
    name: 'showAlgebraInput',
    label: 'Algebra input',
    changeProp: true,
    valueTrue: 'true',
    valueFalse: 'false',
  },
  {
    type: 'select',
    name: 'algebraInputPosition',
    changeProp: true,
    options: [
      { value: 'algebra', name: 'Algebra' },
      { value: 'top', name: 'Top' },
      { value: 'bottom', name: 'Bottom' },
    ],
  },
  {
    type: 'checkbox',
    name: 'showMenuBar',
    label: 'Menu bar',
    changeProp: true,
    valueTrue: 'true',
    valueFalse: 'false',
  },
  {
    type: 'checkbox',
    name: 'showToolBar',
    label: 'Tool bar',
    changeProp: true,
    valueTrue: 'true',
    valueFalse: 'false',
  },
  {
    type: 'checkbox',
    name: 'showToolBarHelp',
    label: 'Tool bar help',
    changeProp: true,
    valueTrue: 'true',
    valueFalse: 'false',
  },
  {
    type: 'checkbox',
    name: 'enableLabelDrags',
    label: 'Drag labels',
    changeProp: true,
    valueTrue: 'true',
    valueFalse: 'false',
  },
  {
    type: 'checkbox',
    name: 'enableShiftDragZoom',
    label: 'Shift drag and zoom',
    changeProp: true,
    valueTrue: 'true',
    valueFalse: 'false',
  },
  {
    type: 'checkbox',
    name: 'showZoomButtons',
    label: 'Zoom buttons',
    changeProp: true,
    valueTrue: 'true',
    valueFalse: 'false',
  },
  {
    type: 'checkbox',
    name: 'errorDialogActive',
    label: 'Error Dialog',
    changeProp: true,
    valueTrue: 'true',
    valueFalse: 'false',
  },
  {
    type: 'checkbox',
    name: 'showResetIcon',
    label: 'Reset icon',
    changeProp: true,
    valueTrue: 'true',
    valueFalse: 'false',
  },
  {
    type: 'checkbox',
    name: 'enableRightClick',
    label: 'Right click',
    changeProp: true,
    valueTrue: 'true',
    valueFalse: 'false',
  },
  {
    type: 'checkbox',
    name: 'allowStyleBar',
    label: 'Style bar',
    changeProp: true,
    valueTrue: 'true',
    valueFalse: 'false',
  },
  {
    type: 'checkbox',
    name: 'randomize',
    label: 'Randomize',
    changeProp: true,
    valueTrue: 'true',
    valueFalse: 'false',
  },
  {
    type: 'checkbox',
    name: 'useBrowserForJS',
    label: 'Browser JS',
    changeProp: true,
    valueTrue: 'true',
    valueFalse: 'false',
  },
  {
    type: 'checkbox',
    name: 'showLogging',
    label: 'Show logs',
    changeProp: true,
    valueTrue: 'true',
    valueFalse: 'false',
  },
  {
    type: 'checkbox',
    name: 'enableFileFeatures',
    label: 'File features',
    changeProp: true,
    valueTrue: 'true',
    valueFalse: 'false',
  },
  {
    type: 'checkbox',
    name: 'enableUndoRedo',
    label: 'Undo redo',
    changeProp: true,
    valueTrue: 'true',
    valueFalse: 'false',
  },
  {
    type: 'checkbox',
    name: 'showAnimationButton',
    label: 'Animation button',
    changeProp: true,
    valueTrue: 'true',
    valueFalse: 'false',
  },
  {
    type: 'checkbox',
    name: 'showFullscreenButton',
    label: 'Fullscreen button',
    changeProp: true,
    valueTrue: 'true',
    valueFalse: 'false',
  },
  {
    type: 'checkbox',
    name: 'showSuggestionButtons',
    label: 'Suggestion buttons',
    changeProp: true,
    valueTrue: 'true',
    valueFalse: 'false',
  },
  {
    type: 'checkbox',
    name: 'showAStartTooltip',
    label: 'Start tooltip',
    changeProp: true,
    valueTrue: 'true',
    valueFalse: 'false',
  },
  {
    type: 'color',
    name: 'borderColor',
    label: 'Border color',
    changeProp: true,
  },
];

//TODO: all app parameters
//https://wiki.geogebra.org/en/Reference:GeoGebra_App_Parameters
